#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# wyb added video ipu
#obj-$(CONFIG_VIDEO_IPUV3) += ipu_csi.o\
#			ipu_idmac.o
obj-$(CONFIG_VIDEO_ADV7280) += adv7280.o board_camera.o
