#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# wyb added video ipu
#obj-$(CONFIG_VIDEO_IPUV3) += ipu_csi.o\
#			ipu_idmac.o
obj-$(CONFIG_VIDEO_IPUV3) += ipu_common_sdk.o ipu_idmac.o ipu_csi.o\
			ipu_vdi.o ipu_ic.o ipu_dp.o ipu_di.o ipu_dc.o ipu_dmfc.o ips_disp_panel.o
